-- MySQL Script generated by MySQL Workbench
-- Mon Nov  3 09:45:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `IdEstado` INT NOT NULL AUTO_INCREMENT,
  `NomeEstado` VARCHAR(20) NULL,
  `siglaEstado` CHAR(2) NULL,
  PRIMARY KEY (`IdEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `IdCidade` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(45) NULL,
  `Estado_cidade` INT NULL,
  PRIMARY KEY (`IdCidade`),
  INDEX `Estado_Cidade_idx` (`Estado_cidade` ASC) VISIBLE,
  CONSTRAINT `Estado_Cidade`
    FOREIGN KEY (`Estado_cidade`)
    REFERENCES `mydb`.`Estado` (`IdEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `IdEndereco` INT NOT NULL AUTO_INCREMENT,
  `NomeEndereco` INT NOT NULL,
  `Logradoro` VARCHAR(45) NULL,
  `num_end` VARCHAR(45) NULL,
  `bairro-end` VARCHAR(45) NULL,
  `Cep_End` VARCHAR(45) NULL,
  `Cidade_End` INT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  PRIMARY KEY (`IdEndereco`),
  INDEX `Cidade_End_idx` (`Cidade_End` ASC) VISIBLE,
  INDEX `fk_Endereco_Cliente1_idx` (`Cliente_IdCliente` ASC) VISIBLE,
  CONSTRAINT `Cidade_End`
    FOREIGN KEY (`Cidade_End`)
    REFERENCES `mydb`.`Cidade` (`IdCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Cliente1`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome_Cliente` VARCHAR(50) NOT NULL,
  `DTN_Cliente` DATE NOT NULL,
  `Email` VARCHAR(70) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `Endereco_IdEndereco` INT NOT NULL,
  `Endereco_NomeEndereco` VARCHAR(45) NOT NULL,
  `Telefone` CHAR(9) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `ClienteSenha` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`IdCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  INDEX `fk_Cliente_Endereco1_idx` (`Endereco_IdEndereco` ASC, `Endereco_NomeEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`Endereco_IdEndereco` , `Endereco_NomeEndereco`)
    REFERENCES `mydb`.`Endereco` (`IdEndereco` , `NomeEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `Nome_Produto` VARCHAR(150) NOT NULL,
  `Preco_Base` DECIMAL(10,2) NOT NULL,
  `Tipo_Produto` ENUM('Pronto', 'Personalizado') NOT NULL,
  `Descricao` TEXT(255) NULL,
  `Ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bolos_Prontos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bolos_Prontos` (
  `IdBolosProntos` INT NOT NULL AUTO_INCREMENT,
  `Tamanho` VARCHAR(45) NOT NULL,
  `Recheio` VARCHAR(45) NOT NULL,
  `Cobertura` VARCHAR(45) NOT NULL,
  `Peso` DECIMAL(5,2) NOT NULL,
  `Imagem_URL` VARCHAR(255) NOT NULL,
  `Quantidade_no_Estoque` INT NOT NULL,
  `IdCategoria` INT NOT NULL,
  `Id_Produto` INT NOT NULL,
  PRIMARY KEY (`IdBolosProntos`),
  INDEX `IdCategoria_idx` (`IdCategoria` ASC) VISIBLE,
  INDEX `Id_Produto_idx` (`Id_Produto` ASC) VISIBLE,
  CONSTRAINT `IdCategoria`
    FOREIGN KEY (`IdCategoria`)
    REFERENCES `mydb`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Id_Produto`
    FOREIGN KEY (`Id_Produto`)
    REFERENCES `mydb`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendas` (
  `idVendas` INT NOT NULL AUTO_INCREMENT,
  `Cliente_Venda` INT NOT NULL,
  `Data_Venda` DATE NOT NULL,
  `Valor_Total` DECIMAL(10,2) NOT NULL,
  `Forma_de_Pagamento` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVendas`),
  INDEX `Cliente_Venda_idx` (`Cliente_Venda` ASC) VISIBLE,
  CONSTRAINT `Cliente_Venda`
    FOREIGN KEY (`Cliente_Venda`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item_Vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item_Vendas` (
  `IdItem_Vendas` INT NOT NULL AUTO_INCREMENT,
  `IdVenda` INT NOT NULL,
  `IdProduto` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Preco_Unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`IdItem_Vendas`),
  INDEX `IdVenda_idx` (`IdVenda` ASC) VISIBLE,
  INDEX `IdProduto_idx` (`IdProduto` ASC) VISIBLE,
  CONSTRAINT `IdVenda`
    FOREIGN KEY (`IdVenda`)
    REFERENCES `mydb`.`Vendas` (`idVendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdProduto`
    FOREIGN KEY (`IdProduto`)
    REFERENCES `mydb`.`Bolos_Prontos` (`IdBolosProntos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `IdProduto` INT NOT NULL,
  `IdCliente` INT NOT NULL,
  `Nota` INT NOT NULL,
  `Comentario` VARCHAR(255) NULL,
  `DataAvaliacao` DATE NOT NULL,
  PRIMARY KEY (`idAvaliacao`),
  INDEX `IdProduto_idx` (`IdProduto` ASC) VISIBLE,
  INDEX `IdClientes_idx` (`IdCliente` ASC) VISIBLE,
  CONSTRAINT `IdProduto`
    FOREIGN KEY (`IdProduto`)
    REFERENCES `mydb`.`Bolos_Prontos` (`IdBolosProntos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdClientes`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstoqueMovimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstoqueMovimentacao` (
  `idEstoqueMovimentacao` INT NOT NULL AUTO_INCREMENT,
  `IdProduto` INT NOT NULL,
  `TipoMovimentacao` VARCHAR(20) NOT NULL,
  `Quantidade` INT NOT NULL,
  `DataMovimentacao` DATE NOT NULL,
  `Observacao` VARCHAR(100) NULL,
  PRIMARY KEY (`idEstoqueMovimentacao`),
  INDEX `IdProduto_idx` (`IdProduto` ASC) VISIBLE,
  CONSTRAINT `IdProduto`
    FOREIGN KEY (`IdProduto`)
    REFERENCES `mydb`.`Bolos_Prontos` (`IdBolosProntos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorias_Opcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorias_Opcoes` (
  `IdCategorias_Opcoes` INT NOT NULL AUTO_INCREMENT,
  `Nome_Categoria` VARCHAR(255) NOT NULL,
  `Ordem_Exibicao` INT NOT NULL,
  `eh_opcional` TINYINT(1) NOT NULL,
  PRIMARY KEY (`IdCategorias_Opcoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Opcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Opcoes` (
  `idOpcoes` INT NOT NULL AUTO_INCREMENT,
  ` id_Categoria_Opcao` INT NOT NULL,
  ` Nome_Opcao` VARCHAR(100) NOT NULL,
  `Custo_Adicional` DECIMAL(10,2) NULL,
  `Opcoescol` VARCHAR(45) NULL,
  PRIMARY KEY (`idOpcoes`),
  INDEX `id_Categoria_Opcao` (` id_Categoria_Opcao` ASC) VISIBLE,
  CONSTRAINT `id_Categoria_Opcao`
    FOREIGN KEY (` id_Categoria_Opcao`)
    REFERENCES `mydb`.`Categorias_Opcoes` (`IdCategorias_Opcoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItemVendaOpcoesEscolhidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemVendaOpcoesEscolhidas` (
  `id_item_venda_opcao` INT NOT NULL AUTO_INCREMENT,
  `id_item_venda` INT NOT NULL,
  `id_opcao` INT NOT NULL,
  PRIMARY KEY (`id_item_venda_opcao`),
  INDEX `id_item_venda_idx` (`id_item_venda` ASC) VISIBLE,
  INDEX `id_opcao_idx` (`id_opcao` ASC) VISIBLE,
  CONSTRAINT `id_item_venda`
    FOREIGN KEY (`id_item_venda`)
    REFERENCES `mydb`.`Item_Vendas` (`IdItem_Vendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_opcao`
    FOREIGN KEY (`id_opcao`)
    REFERENCES `mydb`.`Opcoes` (`idOpcoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
